# Generated by Django 5.2.6 on 2025-09-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripimage',
            name='image_url',
            field=models.TextField(default='', max_length=400),
        ),
    ]
